#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Praveen Perera"
email = "me@praveenperera.com"

[signing]
sign-all = true
backend = "gpg"
key = "E134BCAEA4B75DBE"

[aliases]
stack = ["log", "-r", "(master::@) & (bookmarks() | @)", "--reversed", "-T", "if(bookmarks, bookmarks ++ \"\\n\", if(self.current_working_copy(), \"@ (working copy)\\n\", \"\"))", "--no-graph"]

[remotes.origin]
auto-track-bookmarks = "*"

[ui]
merge-editor = "vscode"
